<?php

namespace Database\Seeds;

use Illuminate\Database\Seeder;

class BravoTermsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bravo_terms')->delete();
        
        \DB::table('bravo_terms')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Cultural',
                'content' => NULL,
                'attr_id' => 1,
                'slug' => 'cultural',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Nature & Adventure',
                'content' => NULL,
                'attr_id' => 1,
                'slug' => 'nature-adventure',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Marine',
                'content' => NULL,
                'attr_id' => 1,
                'slug' => 'marine',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Independent',
                'content' => NULL,
                'attr_id' => 1,
                'slug' => 'independent',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Activities',
                'content' => NULL,
                'attr_id' => 1,
                'slug' => 'activities',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Festival & Events',
                'content' => NULL,
                'attr_id' => 1,
                'slug' => 'festival-events',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Special Interest',
                'content' => NULL,
                'attr_id' => 1,
                'slug' => 'special-interest',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Wifi',
                'content' => NULL,
                'attr_id' => 2,
                'slug' => 'wifi',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Gymnasium',
                'content' => NULL,
                'attr_id' => 2,
                'slug' => 'gymnasium',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Mountain Bike',
                'content' => NULL,
                'attr_id' => 2,
                'slug' => 'mountain-bike',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Satellite Office',
                'content' => NULL,
                'attr_id' => 2,
                'slug' => 'satellite-office',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Staff Lounge',
                'content' => NULL,
                'attr_id' => 2,
                'slug' => 'staff-lounge',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Golf Cages',
                'content' => NULL,
                'attr_id' => 2,
                'slug' => 'golf-cages',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Aerobics Room',
                'content' => NULL,
                'attr_id' => 2,
                'slug' => 'aerobics-room',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Air Conditioning',
                'content' => NULL,
                'attr_id' => 3,
                'slug' => 'air-conditioning',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => 86,
                'icon' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Breakfast',
                'content' => NULL,
                'attr_id' => 3,
                'slug' => 'breakfast',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => 87,
                'icon' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Kitchen',
                'content' => NULL,
                'attr_id' => 3,
                'slug' => 'kitchen',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => 88,
                'icon' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Parking',
                'content' => NULL,
                'attr_id' => 3,
                'slug' => 'parking',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => 89,
                'icon' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Pool',
                'content' => NULL,
                'attr_id' => 3,
                'slug' => 'pool',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => 90,
                'icon' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Wi-Fi Internet',
                'content' => NULL,
                'attr_id' => 3,
                'slug' => 'wi-fi-internet',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => 91,
                'icon' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Wi-Fi miễn phí',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'wake-up-call',
                'create_user' => 1,
                'update_user' => 1,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-24 18:35:20',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Wi-Fi ở nơi công cộng',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'car-hire',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-23 22:03:11',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Bãi biển riêng',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'bicycle-hire',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-23 22:03:34',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Bể bơi trong nhà',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'flat-tv',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-23 22:03:58',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Bể bơi ngoài trời',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'laundry-and-dry-cleaning',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-23 22:04:10',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Phòng tập thể dục',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'internet-wifi',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-23 22:04:30',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Spa',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'coffee-and-tea',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-23 22:04:40',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Havana Lobby bar',
                'content' => NULL,
                'attr_id' => 5,
                'slug' => 'havana-lobby-bar',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Fiesta Restaurant',
                'content' => NULL,
                'attr_id' => 5,
                'slug' => 'fiesta-restaurant',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Hotel transport services',
                'content' => NULL,
                'attr_id' => 5,
                'slug' => 'hotel-transport-services',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Free luggage deposit',
                'content' => NULL,
                'attr_id' => 5,
                'slug' => 'free-luggage-deposit',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Laundry Services',
                'content' => NULL,
                'attr_id' => 5,
                'slug' => 'laundry-services',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Pets welcome',
                'content' => NULL,
                'attr_id' => 5,
                'slug' => 'pets-welcome',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Tickets',
                'content' => NULL,
                'attr_id' => 5,
                'slug' => 'tickets',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Wake-up call',
                'content' => NULL,
                'attr_id' => 6,
                'slug' => 'wake-up-call-1',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => 'icofont-wall-clock',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Flat Tv',
                'content' => NULL,
                'attr_id' => 6,
                'slug' => 'flat-tv-1',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => 'icofont-imac',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Laundry and dry cleaning',
                'content' => NULL,
                'attr_id' => 6,
                'slug' => 'laundry-and-dry-cleaning-1',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => 'icofont-recycle-alt',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Internet – Wifi',
                'content' => NULL,
                'attr_id' => 6,
                'slug' => 'internet-wifi-1',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => 'icofont-wifi-alt',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Coffee and tea',
                'content' => NULL,
                'attr_id' => 6,
                'slug' => 'coffee-and-tea-1',
                'create_user' => NULL,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-15 08:30:07',
                'updated_at' => '2020-09-15 08:30:07',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => 'icofont-tea',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Sòng bạc',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'song-bac',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:04:53',
                'updated_at' => '2020-09-23 22:04:53',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Hội nghị hội thảo',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'hoi-nghi-hoi-thao',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:02',
                'updated_at' => '2020-09-23 22:05:02',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Sân Golf',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'san-golf',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:11',
                'updated_at' => '2020-09-23 22:05:11',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Sân Tennis',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'san-tennis',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:16',
                'updated_at' => '2020-09-23 22:05:16',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Nhà hàng, Khu ăn uống',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'nha-hang-khu-an-uong',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:27',
                'updated_at' => '2020-09-23 22:05:27',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Quán Bar',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'quan-bar',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:31',
                'updated_at' => '2020-09-23 22:05:31',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Khu vui chơi trẻ em',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'khu-vui-choi-tre-em',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:38',
                'updated_at' => '2020-09-23 22:05:38',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Bãi đậu xe ô tô',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'bai-dau-xe-o-to',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:45',
                'updated_at' => '2020-09-23 22:05:45',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Dịch vụ xe đưa đón sân bay',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'dich-vu-xe-dua-don-san-bay',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:52',
                'updated_at' => '2020-09-23 22:05:52',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Dịch vụ giữ đồ',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'dich-vu-giu-do',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:05:58',
                'updated_at' => '2020-09-23 22:05:58',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Dọn phòng hàng ngày',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'don-phong-hang-ngay',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:06:05',
                'updated_at' => '2020-09-23 22:06:05',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Dịch vụ giặt là',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'dich-vu-giat-la',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:06:11',
                'updated_at' => '2020-09-23 22:06:11',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Dịch vụ đặt vé máy bay, tour du lịch',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'dich-vu-dat-ve-may-bay-tour-du-lich',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:06:19',
                'updated_at' => '2020-09-23 22:06:19',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Dịch vụ Karaoke',
                'content' => NULL,
                'attr_id' => 4,
                'slug' => 'dich-vu-karaoke',
                'create_user' => 1,
                'update_user' => NULL,
                'origin_id' => NULL,
                'lang' => NULL,
                'created_at' => '2020-09-23 22:06:30',
                'updated_at' => '2020-09-23 22:06:30',
                'deleted_at' => NULL,
                'image_id' => NULL,
                'icon' => NULL,
            ),
        ));
        
        
    }
}