<?php

namespace Database\Seeds;

use Illuminate\Database\Seeder;

class MediaFilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media_files')->delete();
        
        \DB::table('media_files')->insert(array (
            0 => 
            array (
                'id' => 1,
                'file_name' => 'noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son2-768x51181.jpg',
                'file_path' => 'public/uploads/img/noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son2-768x51181.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 12:44:30',
                'updated_at' => '2022-06-22 12:44:30',
            ),
            1 => 
            array (
                'id' => 2,
                'file_name' => 'noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son3-768x48782.jpg',
                'file_path' => 'public/uploads/img/noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son3-768x48782.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 12:52:34',
                'updated_at' => '2022-06-22 12:52:34',
            ),
            2 => 
            array (
                'id' => 3,
                'file_name' => 'noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son4-768x48059.jpg',
                'file_path' => 'public/uploads/img/noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son4-768x48059.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 12:52:34',
                'updated_at' => '2022-06-22 12:52:34',
            ),
            3 => 
            array (
                'id' => 4,
                'file_name' => 'noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son541.jpg',
                'file_path' => 'public/uploads/img/noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son541.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 12:52:34',
                'updated_at' => '2022-06-22 12:52:34',
            ),
            4 => 
            array (
                'id' => 5,
                'file_name' => 'noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son6-768x51197.jpg',
                'file_path' => 'public/uploads/img/noi-bai-thai-nguyen-bac-kan-cao-bang-lang-son6-768x51197.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 12:52:34',
                'updated_at' => '2022-06-22 12:52:34',
            ),
            5 => 
            array (
                'id' => 6,
                'file_name' => '22393_MM7E6C2YQG_30014039652_b4a2c3e797_c50.jpg',
                'file_path' => 'public/uploads/img/22393_MM7E6C2YQG_30014039652_b4a2c3e797_c50.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:45',
                'updated_at' => '2022-06-22 14:02:45',
            ),
            6 => 
            array (
                'id' => 7,
                'file_name' => '4af1484302070_flc_luxury_hotel_quy_nhon41.jpg',
                'file_path' => 'public/uploads/img/4af1484302070_flc_luxury_hotel_quy_nhon41.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:53',
                'updated_at' => '2022-06-22 14:02:53',
            ),
            7 => 
            array (
                'id' => 8,
                'file_name' => 'flc_luxury_hotel_quy_nhon83.jpg',
                'file_path' => 'public/uploads/img/flc_luxury_hotel_quy_nhon83.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:53',
                'updated_at' => '2022-06-22 14:02:53',
            ),
            8 => 
            array (
                'id' => 9,
                'file_name' => 'j5w1484302125_flc_luxury_hotel_quy_nhon1.jpg',
                'file_path' => 'public/uploads/img/j5w1484302125_flc_luxury_hotel_quy_nhon1.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:53',
                'updated_at' => '2022-06-22 14:02:53',
            ),
            9 => 
            array (
                'id' => 10,
                'file_name' => 'lMYTsRUlRfuHxMystmjuMA-5781.jpg',
                'file_path' => 'public/uploads/img/lMYTsRUlRfuHxMystmjuMA-5781.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:53',
                'updated_at' => '2022-06-22 14:02:53',
            ),
            10 => 
            array (
                'id' => 11,
                'file_name' => 'tzm1541674365_khach_san_flc_luxury_quy_nhon72.jpg',
                'file_path' => 'public/uploads/img/tzm1541674365_khach_san_flc_luxury_quy_nhon72.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:53',
                'updated_at' => '2022-06-22 14:02:53',
            ),
            11 => 
            array (
                'id' => 12,
                'file_name' => 'uUvzlVINQiiHi-9TlasXqQ-130.jpg',
                'file_path' => 'public/uploads/img/uUvzlVINQiiHi-9TlasXqQ-130.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:53',
                'updated_at' => '2022-06-22 14:02:53',
            ),
            12 => 
            array (
                'id' => 13,
                'file_name' => 'uUvzlVINQiiHi-9TlasXqQ-1451.jpg',
                'file_path' => 'public/uploads/img/uUvzlVINQiiHi-9TlasXqQ-1451.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:02:53',
                'updated_at' => '2022-06-22 14:02:53',
            ),
            13 => 
            array (
                'id' => 14,
                'file_name' => '7762633189.jpg',
                'file_path' => 'public/uploads/img/7762633189.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:35',
                'updated_at' => '2022-06-22 14:31:35',
            ),
            14 => 
            array (
                'id' => 15,
                'file_name' => '1Le0qIuQScWGb45NPVTjCQ-6923.jpg',
                'file_path' => 'public/uploads/img/1Le0qIuQScWGb45NPVTjCQ-6923.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            15 => 
            array (
                'id' => 16,
                'file_name' => '3RMfMxL5Q8y5Wa2mwijUEg-784.jpg',
                'file_path' => 'public/uploads/img/3RMfMxL5Q8y5Wa2mwijUEg-784.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            16 => 
            array (
                'id' => 17,
                'file_name' => '4577ca5fbfae9469.jpg',
                'file_path' => 'public/uploads/img/4577ca5fbfae9469.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            17 => 
            array (
                'id' => 18,
                'file_name' => 'a30e987f5147.jpg',
                'file_path' => 'public/uploads/img/a30e987f5147.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            18 => 
            array (
                'id' => 19,
                'file_name' => 'd4796a92e491.jpg',
                'file_path' => 'public/uploads/img/d4796a92e491.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            19 => 
            array (
                'id' => 20,
                'file_name' => 'db6b35761.jpg',
                'file_path' => 'public/uploads/img/db6b35761.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            20 => 
            array (
                'id' => 21,
                'file_name' => 'Mq18GhhaRFiN22w6mSx4-A-152.jpg',
                'file_path' => 'public/uploads/img/Mq18GhhaRFiN22w6mSx4-A-152.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            21 => 
            array (
                'id' => 22,
                'file_name' => 'Mq18GhhaRFiN22w6mSx4-A-1921.jpg',
                'file_path' => 'public/uploads/img/Mq18GhhaRFiN22w6mSx4-A-1921.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            22 => 
            array (
                'id' => 23,
                'file_name' => 'voKATfiiSaulDz9PmXV3Jw-6385.jpg',
                'file_path' => 'public/uploads/img/voKATfiiSaulDz9PmXV3Jw-6385.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            23 => 
            array (
                'id' => 24,
                'file_name' => 'voKATfiiSaulDz9PmXV3Jw-6671.jpg',
                'file_path' => 'public/uploads/img/voKATfiiSaulDz9PmXV3Jw-6671.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:31:45',
                'updated_at' => '2022-06-22 14:31:45',
            ),
            24 => 
            array (
                'id' => 25,
                'file_name' => '42328_9387DUY8WP_flc75.jpg',
                'file_path' => 'public/uploads/img/42328_9387DUY8WP_flc75.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:09',
                'updated_at' => '2022-06-22 14:39:09',
            ),
            25 => 
            array (
                'id' => 26,
                'file_name' => '_dsc347125.jpg',
                'file_path' => 'public/uploads/img/_dsc347125.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            26 => 
            array (
                'id' => 27,
                'file_name' => '_dsc638589.jpg',
                'file_path' => 'public/uploads/img/_dsc638589.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            27 => 
            array (
                'id' => 28,
                'file_name' => '_mg_18677.jpg',
                'file_path' => 'public/uploads/img/_mg_18677.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            28 => 
            array (
                'id' => 29,
                'file_name' => '42328_LIJDXLB0L214.jpg',
                'file_path' => 'public/uploads/img/42328_LIJDXLB0L214.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            29 => 
            array (
                'id' => 30,
                'file_name' => '42328_YMS10E1XB264.jpg',
                'file_path' => 'public/uploads/img/42328_YMS10E1XB264.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            30 => 
            array (
                'id' => 31,
                'file_name' => '37275436412_b3891d75f4_o50.jpg',
                'file_path' => 'public/uploads/img/37275436412_b3891d75f4_o50.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            31 => 
            array (
                'id' => 32,
                'file_name' => 'dsc0935856.jpg',
                'file_path' => 'public/uploads/img/dsc0935856.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            32 => 
            array (
                'id' => 33,
                'file_name' => 'gracio-cafe99.jpg',
                'file_path' => 'public/uploads/img/gracio-cafe99.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            33 => 
            array (
                'id' => 34,
                'file_name' => 'img_86460.jpg',
                'file_path' => 'public/uploads/img/img_86460.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            34 => 
            array (
                'id' => 35,
                'file_name' => 'img_898726.jpg',
                'file_path' => 'public/uploads/img/img_898726.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            35 => 
            array (
                'id' => 36,
                'file_name' => 'img_901974.jpg',
                'file_path' => 'public/uploads/img/img_901974.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            36 => 
            array (
                'id' => 37,
                'file_name' => 'img_933438.jpg',
                'file_path' => 'public/uploads/img/img_933438.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            37 => 
            array (
                'id' => 38,
                'file_name' => 'img-84a40f0b6372.jpg',
                'file_path' => 'public/uploads/img/img-84a40f0b6372.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            38 => 
            array (
                'id' => 39,
                'file_name' => 'img-ca0269328.jpg',
                'file_path' => 'public/uploads/img/img-ca0269328.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            39 => 
            array (
                'id' => 40,
                'file_name' => 'overview_38505664952_o41.jpg',
                'file_path' => 'public/uploads/img/overview_38505664952_o41.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            40 => 
            array (
                'id' => 41,
                'file_name' => 'salt-water-swimming-pool16.jpg',
                'file_path' => 'public/uploads/img/salt-water-swimming-pool16.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            41 => 
            array (
                'id' => 42,
                'file_name' => 'toan-canh-153.png',
                'file_path' => 'public/uploads/img/toan-canh-153.png',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            42 => 
            array (
                'id' => 43,
                'file_name' => 'toan-canh-37.jpg',
                'file_path' => 'public/uploads/img/toan-canh-37.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            43 => 
            array (
                'id' => 44,
                'file_name' => 'toan-canh-567.jpg',
                'file_path' => 'public/uploads/img/toan-canh-567.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            44 => 
            array (
                'id' => 45,
                'file_name' => 'toan-canh-bai-bien-ss22.jpg',
                'file_path' => 'public/uploads/img/toan-canh-bai-bien-ss22.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:39:21',
                'updated_at' => '2022-06-22 14:39:21',
            ),
            45 => 
            array (
                'id' => 46,
                'file_name' => 'da91511235544_khach_san_flc_grand_sam_son26.jpg',
                'file_path' => 'public/uploads/img/da91511235544_khach_san_flc_grand_sam_son26.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:33',
                'updated_at' => '2022-06-22 14:45:33',
            ),
            46 => 
            array (
                'id' => 47,
                'file_name' => '1_khach_san_flc_grand_sam_son77.jpg',
                'file_path' => 'public/uploads/img/1_khach_san_flc_grand_sam_son77.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            47 => 
            array (
                'id' => 48,
                'file_name' => '1cb1511235481_khach_san_flc_grand_sam_son26.jpg',
                'file_path' => 'public/uploads/img/1cb1511235481_khach_san_flc_grand_sam_son26.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            48 => 
            array (
                'id' => 49,
                'file_name' => '2khach_san_flc_grand_sam_son31.jpg',
                'file_path' => 'public/uploads/img/2khach_san_flc_grand_sam_son31.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            49 => 
            array (
                'id' => 50,
                'file_name' => '7z98k1Y-RlWtLdA1fCBiDA-531.jpg',
                'file_path' => 'public/uploads/img/7z98k1Y-RlWtLdA1fCBiDA-531.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            50 => 
            array (
                'id' => 51,
                'file_name' => '9s31511235515_khach_san_flc_grand_sam_son41.jpg',
                'file_path' => 'public/uploads/img/9s31511235515_khach_san_flc_grand_sam_son41.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            51 => 
            array (
                'id' => 52,
                'file_name' => '42294_C6PRARBEDT_gym-club-2_26760688039_o63.jpg',
                'file_path' => 'public/uploads/img/42294_C6PRARBEDT_gym-club-2_26760688039_o63.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            52 => 
            array (
                'id' => 53,
                'file_name' => '42294_T8QEDK66MS_lobby-3_38536307151_o6.jpg',
                'file_path' => 'public/uploads/img/42294_T8QEDK66MS_lobby-3_38536307151_o6.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            53 => 
            array (
                'id' => 54,
                'file_name' => 'bqi1511235516_khach_san_flc_grand_sam_son63.jpg',
                'file_path' => 'public/uploads/img/bqi1511235516_khach_san_flc_grand_sam_son63.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            54 => 
            array (
                'id' => 55,
                'file_name' => 'jou1511235543_khach_san_flc_grand_sam_son0.jpg',
                'file_path' => 'public/uploads/img/jou1511235543_khach_san_flc_grand_sam_son0.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            55 => 
            array (
                'id' => 56,
                'file_name' => 'khach_san_flc_grand_sam_son31.jpg',
                'file_path' => 'public/uploads/img/khach_san_flc_grand_sam_son31.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            56 => 
            array (
                'id' => 57,
                'file_name' => 'puh1511235496_khach_san_flc_grand_sam_son22.jpg',
                'file_path' => 'public/uploads/img/puh1511235496_khach_san_flc_grand_sam_son22.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 9,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-22 14:45:43',
                'updated_at' => '2022-06-22 14:45:43',
            ),
            57 => 
            array (
                'id' => 58,
                'file_name' => '177238220.jpg',
                'file_path' => 'public/uploads/img/177238220.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:16',
                'updated_at' => '2022-06-27 10:23:16',
            ),
            58 => 
            array (
                'id' => 59,
                'file_name' => '8689601994.jpg',
                'file_path' => 'public/uploads/img/8689601994.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:24',
                'updated_at' => '2022-06-27 10:23:24',
            ),
            59 => 
            array (
                'id' => 60,
                'file_name' => '15243219173.jpg',
                'file_path' => 'public/uploads/img/15243219173.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:24',
                'updated_at' => '2022-06-27 10:23:24',
            ),
            60 => 
            array (
                'id' => 61,
                'file_name' => '19150276478.jpg',
                'file_path' => 'public/uploads/img/19150276478.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:24',
                'updated_at' => '2022-06-27 10:23:24',
            ),
            61 => 
            array (
                'id' => 62,
                'file_name' => '21774356558.jpg',
                'file_path' => 'public/uploads/img/21774356558.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:24',
                'updated_at' => '2022-06-27 10:23:24',
            ),
            62 => 
            array (
                'id' => 63,
                'file_name' => '24604055179.jpg',
                'file_path' => 'public/uploads/img/24604055179.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:24',
                'updated_at' => '2022-06-27 10:23:24',
            ),
            63 => 
            array (
                'id' => 64,
                'file_name' => '24604084517.jpg',
                'file_path' => 'public/uploads/img/24604084517.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:24',
                'updated_at' => '2022-06-27 10:23:24',
            ),
            64 => 
            array (
                'id' => 65,
                'file_name' => '24604088098.jpg',
                'file_path' => 'public/uploads/img/24604088098.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-06-27 10:23:24',
                'updated_at' => '2022-06-27 10:23:24',
            ),
            65 => 
            array (
                'id' => 66,
                'file_name' => '21952662399.jpg',
                'file_path' => 'public/uploads/img/21952662399.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-07-25 09:44:41',
                'updated_at' => '2022-07-25 09:44:41',
            ),
            66 => 
            array (
                'id' => 67,
                'file_name' => '21952689132.jpg',
                'file_path' => 'public/uploads/img/21952689132.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-07-25 09:46:07',
                'updated_at' => '2022-07-25 09:46:07',
            ),
            67 => 
            array (
                'id' => 68,
                'file_name' => '21952689862.jpg',
                'file_path' => 'public/uploads/img/21952689862.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-07-25 09:46:07',
                'updated_at' => '2022-07-25 09:46:07',
            ),
            68 => 
            array (
                'id' => 69,
                'file_name' => '21952691997.jpg',
                'file_path' => 'public/uploads/img/21952691997.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-07-25 09:46:07',
                'updated_at' => '2022-07-25 09:46:07',
            ),
            69 => 
            array (
                'id' => 70,
                'file_name' => '21952692517.jpg',
                'file_path' => 'public/uploads/img/21952692517.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-07-25 09:46:07',
                'updated_at' => '2022-07-25 09:46:07',
            ),
            70 => 
            array (
                'id' => 71,
                'file_name' => '2195269349.jpg',
                'file_path' => 'public/uploads/img/2195269349.jpg',
                'file_size' => '',
                'file_type' => '',
                'file_extension' => '',
                'create_user' => -1,
                'update_user' => 11,
                'deleted_at' => NULL,
                'app_id' => NULL,
                'app_user_id' => NULL,
                'file_width' => NULL,
                'file_height' => NULL,
                'created_at' => '2022-07-25 09:46:07',
                'updated_at' => '2022-07-25 09:46:07',
            ),
        ));
        
        
    }
}